### ISSUE TITLE
Status? Relevant? Bug reported?

### ISSUE THREAD

**Issue by supersexy** [HRomie/dropbear-init-fix#1]
Hi, thanks for your work on this! I have a few questions: 

- is this still relevant?
- is this fixed by Ubuntu devs?
- does exist a [bug report](https://launchpad.net/ubuntu/+source/busybox/+bugs) for this?
- what can be done to avoid having this in Ubuntu 20.04?

**Comment by HRomie** [comment]
Hi,

> is this still relevant?

If you're running Ubuntu 18.04, yes, it is still relevant.

> is this fixed by Ubuntu devs?

This bug has been fixed in later Ubuntu releases (18.10 and above), but the fix has never made it into 18.04. (To be exact, this issue has been fixed in [dropbear-initramfs 2018.76-3](https://changelogs.ubuntu.com/changelogs/pool/universe/d/dropbear/dropbear_2018.76-3/changelog))

> does exist a bug report for this?

Yes, you can find the bug report for this [here](https://bugs.launchpad.net/ubuntu/+source/dropbear/+bug/1652091)

> what can be done to avoid having this in Ubuntu 20.04?

Most likely nothing needs to be done, as newer versions of dropbear-initramfs do not suffer from this bug.

**Comment by supersexy** [comment]
Thank you very much for the update! Have a nice day!
